version: '3.8'

services:
  app:
    build: .
    ports:
      - "5086:5086"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
